### ISSUE TITLE
Testing bulkactivity in moodle 3.8

### ISSUE THREAD

**Issue by kdidier51** [doiphode/moodle-block_bulkactivity#1]
Hello,
I have installed bulkactivity because I used sharing cart and I have problem with it on moodle 3.8.
But I have the same problem with bulkactivity than with sharing cart :  "More exactly, every time we turn edition on, all edition button freezes. Then, if we purge all caches and return to course, that's ok. But if in sequence we turn edition off and on again, the freezing problem returns". The problem seems to be the same in all themes. In the console F12, there is an big message error in red. I can give you (in a personnal message) a login and a password on my test plateform to see this message. 
My theme is Fordson. 
Can you explain that ?
Thanks a lot for your answers. 
Didier CABY - REIMS (France)

**Comment by doiphode** [comment]
Hi,

May I ask which version of the plugin are you using?

I realised the issue three weeks ago and pushed an update on 22nd Jan.

Please use the latest commit b908c083616282f2f5c2a63129852b45c6f089f5 and
let me know.

Kind regards,
Shubhendra

**Comment by kdidier51** [comment]
Hello,
Thank you for your quick return. 
I have found you block this morning on github. So I have insalled the latest version : 2019012002.
![Capture3](https://user-images.githubusercontent.com/29543774/74106610-ae3aea00-4b68-11ea-9734-2ac1c071b2c6.PNG)
Best regards
Didier

**Comment by kdidier51** [comment]
Hello,
Thank you for your quick return. 
I have found your block this morning. So I have installed the version on github : 2019012002
![Capture3](https://user-images.githubusercontent.com/29543774/74106696-24d7e780-4b69-11ea-8781-48fbe31857ef.PNG)
Best regards
Didier

**Comment by doiphode** [comment]
Hi,

I have just tested this on 3.8 and it works fine. As mentioned previously the clash between this plugin when used in conjunction with the Sharing cart was resolved in d656541d75162ae0b0fbdaf01c43d832a390835f

The class name was changed for this. The function backup which is also in sharing cart was updated to backupbulk in bulkactivity.

Can you uninstall the plugin and reinstall with the latest code please?

Thanks,
Shubhendra

**Comment by doiphode** [comment]
Hi Didier,

Can you confirm please that you were able to get this working?

Thanks,
Shubhendra

**Comment by kdidier51** [comment]
Hi Shubhendra,
For the moment, the plugin does not work on my platform. 
I have uploaded the tree d656541d75
I have always the same message in the console when I turn edition on. A big red message. 
Here is the end of the message.
I try to find the solution. I delete one by one the others plugins. 
If you want a login and password on my platform, I can give you. 
If I find something, I come back to tell you the good news. 
Sorry if my english is not perfect. 
Best regards
Didier

makeError | @ | require.min.js:5
-- | -- | --
  | v | @ | require.min.js:5
  | o | @ | require.min.js:5
  | requirejs | @ | require.min.js:5
  | (anonymous) | @ | view.php?id=939&notifyeditingon=1:3602
  | execCb | @ | require.min.js:5
  | check | @ | require.min.js:5
  | (anonymous) | @ | require.min.js:5
  | (anonymous) | @ | require.min.js:5
  | (anonymous) | @ | require.min.js:5
  | each | @ | require.min.js:5
  | emit | @ | require.min.js:5
  | check | @ | require.min.js:5
  | enable | @ | require.min.js:5
  | init | @ | require.min.js:5
  | h | @ | require.min.js:5
  | completeLoad | @ | require.min.js:5
  | onScriptLoad | @ | require.min.js:5
  | load (async) |   |  
  | req.load | @ | require.min.js:5
  | load | @ | require.min.js:5
  | load | @ | require.min.js:5
  | fetch | @ | require.min.js:5
  | check | @ | require.min.js:5
  | enable | @ | require.min.js:5
  | enable | @ | require.min.js:5
  | (anonymous) | @ | require.min.js:5
  | (anonymous) | @ | require.min.js:5
  | each | @ | require.min.js:5
  | enable | @ | require.min.js:5
  | init | @ | require.min.js:5
  | (anonymous) | @ | require.min.js:5
  | setTimeout (async) |   |  
  | req.nextTick | @ | require.min.js:5
  | o | @ | require.min.js:5
  | requirejs | @ | require.min.js:5
  | (anonymous) | @ | view.php?id=939&notifyeditingon=1:3600

**Comment by doiphode** [comment]
Hi Didier,

I would be interested to test this on your installation, can you send the details on my email?

doiphode.sunny@gmail.com

Thanks,
Shubhendra

**Comment by kdidier51** [comment]
Hi Subhendra,
I have tried the plugin on Chrome, Opera, FireFox : it's not working
But with Microsoft Edge : all is Ok.
Note that the problem is the same with the block sharing_cart.
Best Regards
Didier
