### ISSUE TITLE
A "Could not delete module from existing section" message when copying items

### ISSUE THREAD

**Issue by acquaalta** [doiphode/moodle-block_bulkactivity#13]
Hi,

**Moodle version:** 3.9
**Plugin version:** 3.9, release 1 (2019012002) - The plugin info in the "Plugins Overview" page says it's the "3.6, release 1" version, but I installed the v3.9 version. I guess it's the following issue:
https://github.com/doiphode/moodle-block_bulkactivity/issues/12

**Problem:**
When trying to copy some items in a course, after choosing the relevant courses to copy to, the item is copied to the courses I chose, but the "Could not delete module from existing section" message is displayed.
To the best of my knowledge the plugin is supposed to **copy** items, and not **move** them. So why does it try to delete a module from an existing section?

Please clarify this issue.

Thanks in advance :-)

![bacplugerror](https://user-images.githubusercontent.com/51836675/102764868-7c97cf80-4384-11eb-8da1-4072081d5a42.png)

**Comment by doiphode** [comment]
I used "Duplicate" feature of Moodle, it has used Moodle's Backup - Restore API. It seems it tries to delete backup file after restoration, and giving that message. The message is being displayed by Moodle core.
