### ISSUE TITLE
Suggestion: Add sequence position

### ISSUE THREAD

**Issue by SolutionsDEV** [doiphode/moodle-block_bulkactivity#17]
Hello,

I tried the plugin in Moodle 4.3.3, it is wonderful, although it has some inconstancy in the menus in the course.

When adding a copy of the activity, it adds it to the end of the section.

My suggestion is to add a field to identify the location, for example first in the selected section, second, third, last and so on. The identified in the database in "sequence" in "course_sections" table.

On the other hand, the section selection provides sections 0, 1 and last section. It would be good to have selection of other possible sections like a number identified. In this case, the user/admin should be well aware of the courses structure.

Last but not least, if you could update the plugin.

Thanks for the good job.

**Comment by doiphode** [comment]
Hi,

I have resolved this in the latest update.

Please use it.

Thanks,
S
