### ISSUE TITLE
Does not work in PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [doiphode/moodle-block_bulkactivity#4]
There is a MySQL specific SQL used making the plugin fail on PostgreSQL:

![image](https://user-images.githubusercontent.com/85831/81966977-8bfab180-961a-11ea-834b-69013c4a4525.png)

**Comment by mudrd8mz** [comment]
https://stackoverflow.com/a/4105810

**Comment by mudrd8mz** [comment]
It's used in other queries too.

**Comment by doiphode** [comment]
Resolved with 54b9a23d0d0557d5641867d360d1bb0f066540e3
