### ISSUE TITLE
Better handle the case of no more courses available

### ISSUE THREAD

**Issue by mudrd8mz** [doiphode/moodle-block_bulkactivity#8]
![image](https://user-images.githubusercontent.com/85831/94340124-8ddc7480-ffff-11ea-9bbc-e9f4091a339d.png)

![image](https://user-images.githubusercontent.com/85831/94340127-9765dc80-ffff-11ea-9432-0a53ae1c9b29.png)

**Comment by doiphode** [comment]
This issue has been resolved in commit 30ac82f0ad3ab96e02f07154b5189fba39928109
Also the plugin has been updated with v3.9 compatibility.
